format = """
[â•­â”€userâ”€â”€â”€â¯](bold blue) $username
[â”£â”€systemâ”€â¯](bold yellow) $hostname
[â”£â”€projectâ¯](bold red) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
[â•°â”€cmdâ”€â”€â”€â”€â¯](bold green) 
"""

[username]
format = "[$user]($style) "
style_user = "green bold"
style_root = "red bold"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "."
style = "yellow bold"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "â€¦/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = " "
untracked = " "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "è¥"
deleted = " "

[golang]
format = "via [ğŸğŸ’¨ $version](bold cyan) "

[nodejs]
format = "via [â¬¢ $version](bold green) "

[python]
format = "via [ğŸ $version](bold yellow) "

[rust]
format = "via [âš™ï¸ $version](red bold) "
